#import "HelloKocherla.h"

@implementation HelloKocherla

RCT_EXPORT_MODULE(HelloKocherla)
- (void)getMessage: (RCTPromiseResolveBlock)resolve
          rejecter: (RCTPromiseRejectBlock)reject
{
    NSString *message = @"Hello Kocherla!";
    resolve(message);
}

// This is the boilerplate method to hook into the New Architecture (TurboModule)
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  // "NativeHelloKocherlaSpec_LegacyAdapter" is a class GENERATED by Codegen
  return std::make_shared<facebook::react::NativeHelloKocherlaSpec_LegacyAdapter>(params);
}

@end
